version: '2'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: '%'
    env_file:
      - .env
  app:
    container_name: scam_bbc
    build: app
    restart: always
    environment:
      MYSQL_HOST: db
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 7621
  nginx:
    container_name: scam_bbc_nginx
    image: website-nginx:v-0.0.1
    build: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app
